name: Deploy Pages

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Set up JDK 9
        uses: actions/setup-java@v1
        with:
          java-version: 9

      - name: Bump Version
        run: mvn versions:set -DgenerateBackupPoms=false -DremoveSnapshot

      - name: Build
        run: mvn --update-snapshots install

      - name: Generate Docs
        run: mvn -pl core clean javadoc:javadoc

      - name: Commit Change
        run: |
          git commit -a -m "Create $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) release"
          git push

      - name: Create Tag
        run: |
          git tag $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          git push --tags

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: core/target/site/apidocs/doxy
          CLEAN: true