name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Set up JDK 9
        uses: actions/setup-java@v1
        with:
          java-version: 9

      - name: Bump Version
        run: mvn --batch-mode versions:set -DgenerateBackupPoms=false -DremoveSnapshot

      - name: Build
        run: mvn --batch-mode --update-snapshots install

      - name: Generate Docs
        run: mvn --batch-mode -pl core clean javadoc:javadoc

      - name: Commit Change
        run: |
          git config --global user.name 'samblake'
          git config --global user.email 'samblake@users.noreply.github.com'
          git commit -a -m "Create $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) release"
          git remote set-url --push origin https://samblake:$GITHUB_TOKEN@github.com/samblake/rexy
          git push

      - name: Create Tag
        run: |
          git tag $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          git push --tags

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: core/target/site/apidocs/doxy
          CLEAN: true
