name: Deploy Pages

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Set up JDK 9
        uses: actions/setup-java@v1
        with:
          java-version: 9

      - name: Bump Version
        run: mvn --batch-mode versions:set -DremoveSnapshot

      - name: Build
        run: mvn --batch-mode --update-snapshots install

      - name: Generate Docs
        run: mvn --batch-mode -pl core clean javadoc:javadoc

      - name: Get Version
        run: echo "rel_ver=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Commit change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Create $rel_ver release
          tagging_message: $rel_ver

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: core/target/site/apidocs/doxy
          CLEAN: true